version: '3'

services:
  gp3-annotation:
    container_name: gp3-annotation
    build:
      context: .
      dockerfile: gp3-annotation/Dockerfile
  annotator:
    container_name: annotator
    build:
      context: .
      dockerfile: annotator/Dockerfile
    ports:
      - "8080:8080"
